[tox]
envlist =
    py{311,312}-django{51,52}
    py312-django60
skipsdist = True

[testenv]
deps =
    django51: Django>=5.1,<5.2
    django52: Django>=5.2,<5.3
    django60: Django>=6.0,<6.1
    pytest
    pytest-django
    pytest-cov
    psycopg2-binary
commands =
    pytest {posargs}
setenv =
    DJANGO_SETTINGS_MODULE = tests.settings
    DATABASE_URL = {env:DATABASE_URL:postgres://postgres:postgres@localhost:5432/test_django_rls}
